name: App Deploy
on:
  push:
    branches:
      - master
  schedule:
    - cron: "12 3 * * SUN"

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.0.100'
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/checkout@v1
        with:
          repository: crystal-pool/Dump
          fetch-depth: 2
          ref: master
      - name: Build Prep
        shell: pwsh
        run: ./scripts/prep.ps1
      - name: Build
        shell: pwsh
        run: ./scripts/build.ps1
