name: App Deploy
on: push
  jobs:
    build:
      name: Build & Deploy
      runs-on: ubuntu-latest
      env:
      - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      - DOTNET_CLI_TELEMETRY_OPTOUT: 1
      steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Build Prep
        shell: pwsh
        run: ./scripts/prep.ps1
      - name: Build
        shell: pwsh
        run: ./scripts/build.ps1
